# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: E2E Test Web
on:
  pull_request:
    branches: [master]
  push:
    paths:
      - "web/**"
      - "core/server/tests/e2e-web/**"
      - ".github/workflows/e2e-web.yml"
  workflow_dispatch:

env:
  IGGY_CI_BUILD: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

permissions:
  contents: read
  security-events: write
  pull-requests: read

jobs:
  test:
    runs-on: ubuntu-latest
    name: ubuntu-latest / stable
    env:
      WEBDRIVER_PORT: 4444
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - name: Setup Rust & system libs
        uses: ./.github/actions/utils/setup-rust-with-cache
        with:
          cache-targets: false
          show-stats: false
      # since our test server image is built from "runtime-prebuilt", we should
      # prepare the front-end distribution outselves (for the normal runtime -
      # a dedicated instruction in the Dockerfile covers this); Iggy Server will
      # then have Web UI embedded and will serve it same origin
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "22"
      - name: Prepare Iggy Web UI distribution
        run: npm --prefix web ci && npm --prefix web run build:static
      - name: Build Iggy server Docker image
        uses: ./.github/actions/utils/docker-build-test-server
        with:
          # if we decide to change the image name or tag here, let's not forget
          # to update `E2E_TEST_IGGY_IMAGE_NAME` and `E2E_TEST_IGGY_IMAGE_TAG`
          # environment variables in step below accordingly
          image-tag: "apache/iggy:test"
          profile: "release"
      - name: Launch web driver
        run: chromedriver --port=${{ env.WEBDRIVER_PORT}} &
      - name: Run end-to-end tests (in release mode)
        run: cargo test --release --test e2e-web
        env:
          E2E_TEST: true
          E2E_TEST_HEADLESS: true
          E2E_TEST_WAIT_TIMEOUT: 10
          E2E_TEST_IGGY_IMAGE_NAME: "apache/iggy"
          E2E_TEST_IGGY_IMAGE_TAG: "test"

